# Deepen roofs & materials thin sections in elements.ts
path = 'src/data/elements.ts'
src = open(path, encoding='utf-8', errors='replace').read()

replacements = [
    # ---- Roofs: Hip Roof (Wudian) ----
    (
        "body: 'Four sloping planes meet at a single horizontal ridge, making this the most prestigious of all roof forms. Double-eaved versions — where a second, shorter roof section projects below the main one — were reserved for the highest imperial halls, such as the Hall of Supreme Harmony (1420, rebuilt 1695). The form\\'s stability and completeness symbolized the absolute authority of the ruler; no commoner building could employ it under penalty of law.'",
        "body: 'Four sloping planes meet at a single horizontal ridge, making this the most prestigious of all roof forms. Double-eaved versions — where a second, shorter roof section projects below the main one — were reserved for the highest imperial halls, such as the Hall of Supreme Harmony (1420, rebuilt 1695). The form\\'s stability and completeness symbolized the absolute authority of the ruler; no commoner building could employ it under penalty of law.\\n\\nThe hierarchy was enforced in practice: a Ming official named in the Veritable Records was demoted for roofing his mansion with a hip roof, and the rule survived into the Qing code. Only the emperor\\'s throne halls, the most sacred temples, and — after a specific imperial grant — the main halls of a few grand Confucian academies were permitted the form. Standing before such a roof, a literate observer could read the building\\'s rank instantly: the wudian is the single most powerful status symbol in Chinese architecture.'"
    ),
    # ---- Roofs: Hip-and-Gable (Xieshan) ----
    (
        "body: 'A hybrid that joins hip slopes on the upper portion with gable ends on the lower portion, creating a distinctive \\'shouldered\\' silhouette. Ranking second in the official hierarchy, it was the standard form for important buildings below the imperial summit: palaces, temples, official halls, and the mansions of princes. The Tiananmen Gate, the Drum Tower, and most main halls of Buddhist temples use the xieshan form.'",
        "body: 'A hybrid that joins hip slopes on the upper portion with gable ends on the lower portion, creating a distinctive \\'shouldered\\' silhouette. Ranking second in the official hierarchy, it was the standard form for important buildings below the imperial summit: palaces, temples, official halls, and the mansions of princes. The Tiananmen Gate, the Drum Tower, and most main halls of Buddhist temples use the xieshan form.\\n\\nBecause the gable end breaks the continuous slope, builders could open windows in the upper wall — which is why the xieshan became the standard for multi-story structures like drum towers, gate towers, and the upper levels of pagodas. The double-eaved xieshan, a rung below the imperial wudian, crowns the main halls of major temples such as the Daxiongbaodian at Beijing\\'s Lama Temple. In the Forbidden City itself, the side gates and secondary halls — including the Meridian Gate\\'s five pavilions — all employ it, so that even the second-ranking form is still overwhelmingly imperial.'"
    ),
    # ---- Roofs: Overhanging Gable (Xuanshan) ----
    (
        "body: 'The gable roof whose eaves extend well beyond the end walls, sheltering the masonry and timber wall-plates from rain. This is the form of choice in southern China, where monsoon rainfall is heavy, and it was long the standard for common dwellings in the Yangtze valley. The projecting gable ends often carry small carved ornaments — the xuanyu (\\'hanging fish\\') and rensui (\\'kindling strips\\') — that both decorate and protect the exposed rafters.'",
        "body: 'The gable roof whose eaves extend well beyond the end walls, sheltering the masonry and timber wall-plates from rain. This is the form of choice in southern China, where monsoon rainfall is heavy, and it was long the standard for common dwellings in the Yangtze valley — from the whitewashed water-town houses of Jiangnan to the timber-frame homes of Sichuan and Hunan.\\n\\nThe projecting gable ends often carry small carved ornaments — the xuanyu (\\'hanging fish\\') and rensui (\\'kindling strips\\') — that both decorate and protect the exposed rafters. The xuanyu is usually carved as a fish, a water creature chosen to protect the building from fire, and its shape changed with local fashion: simple boards in Anhui, elaborate openwork in Jiangsu. Despite its commoner status, the xuanshan remained the technical ancestor of all Chinese roofing: its deep, sheltering overhang is the form from which the imperial hip roof evolved.'"
    ),
    # ---- Roofs: Flush Gable (Yingshan) ----
    (
        "body: 'A gable roof whose ends stop flush with the gable walls, so the roofline is hidden behind brick parapets. The design suits the drier climate of northern China, where rain does not demand overhanging eaves, and it became the most common roof of Ming-Qing houses — including the siheyuan courtyards of Beijing. The brick gables also served as fire barriers between tightly packed houses in city lanes.'",
        "body: 'A gable roof whose ends stop flush with the gable walls, so the roofline is hidden behind brick parapets. The design suits the drier climate of northern China, where rain does not demand overhanging eaves, and it became the most common roof of Ming-Qing houses — including the siheyuan courtyards of Beijing.\\n\\nThe brick gables also served as fire barriers between tightly packed houses in city lanes: in the great conflagrations that periodically swept Beijing, a row of yingshan gables could stop a blaze from leaping house to house. Their plain parapets became a canvas for status display in Huizhou architecture, where the gable tops rise into the famous matouqiang (horse-head walls) — stepped silhouettes that climb above the roofline, still acting as fire breaks but now among the most photographed forms in Chinese vernacular building.'"
    ),
    # ---- Roofs: Pyramidal (Cuanjian) ----
    (
        "body: 'All slopes converge at a single point, crowned by a finial — the form used for pavilions, pagodas, and altars. The most famous example is the Hall of Prayer for Good Harvests at the Temple of Heaven (1545): a triple-eaved cuanjian roof in deep blue tile rising 38 meters as the visual climax of the altar complex. Single-eaved versions crown countless garden pavilions across China.'",
        "body: 'All slopes converge at a single point, crowned by a finial — the form used for pavilions, pagodas, and altars. The most famous example is the Hall of Prayer for Good Harvests at the Temple of Heaven (1545): a triple-eaved cuanjian roof in deep blue tile rising 38 meters as the visual climax of the altar complex.\\n\\nThe single-eaved version crowns countless garden pavilions across China — from the lakeside pavilions of Suzhou to the hilltop kiosks of the Summer Palace — where the finial\\'s gilded orb (baoding) becomes the composition\\'s focal point. The form is also the natural choice for pagodas: since all sides slope equally, the cuanjian reads the same from every direction, which is why Buddhist stupas and many octagonal pagodas adopt it. In the garden, the pyramidal roof\\'s one-point convergence gives a pavilion a vertical accent that terminates a vista or marks a turn in a walkway.'"
    ),
    # ---- Materials: The Timber Frame ----
    (
        "body: 'Unlike the load-bearing masonry walls of the West, Chinese buildings were supported entirely by an internal skeleton of timber columns and beams. Walls did not carry weight — they merely enclosed space. This allowed builders to vary window openings freely and made the structure remarkably resilient: during earthquakes, the flexible frame could sway and absorb energy while masonry walls would crack. The timber frame was assembled with mortise-and-tenon joints and wooden pegs, without nails or glue. The oldest surviving example, the East Hall of Foguang Temple (857 CE), still stands 1,100 years after construction.'",
        "body: 'Unlike the load-bearing masonry walls of the West, Chinese buildings were supported entirely by an internal skeleton of timber columns and beams. Walls did not carry weight — they merely enclosed space. This allowed builders to vary window openings freely and made the structure remarkably resilient: during earthquakes, the flexible frame could sway and absorb energy while masonry walls would crack.\\n\\nThe timber frame was assembled with mortise-and-tenon joints and wooden pegs, without nails or glue. The proof of the system is written in disaster records: during the 1976 Tangshan earthquake, the 984 CE timber Guanyin Pavilion of Dule Temple stood intact while concrete buildings collapsed around it, and the 67-meter Yingxian Pagoda has absorbed more than 40 recorded earthquakes in 970 years. The oldest surviving frame, the East Hall of Foguang Temple (857 CE), still stands 1,100 years after construction — and its columns, like all Chinese columns, were not fixed to the foundation but simply seated on stone plinths, free to shift slightly without cracking.'"
    ),
    # ---- Materials: Rammed Earth and Foundations ----
    (
        "body: 'Before the first timber column was raised, builders laid a platform of hangtu — rammed earth — created by compacting layers of soil, gravel, and lime between wooden forms. These platforms elevated buildings above damp ground and floodwater and provided a stable, level base. The technique dates back to the Shang dynasty (1600-1046 BCE) and was used for everything from humble dwellings to the Great Wall. Rammed earth is extraordinarily durable: sections of the Wall built over 2,000 years ago still stand today.'",
        "body: 'Before the first timber column was raised, builders laid a platform of hangtu — rammed earth — created by compacting layers of soil, gravel, and lime between wooden forms. These platforms elevated buildings above damp ground and floodwater and provided a stable, level base. The technique dates back to the Shang dynasty (1600-1046 BCE) and was used for everything from humble dwellings to the Great Wall and the monumental foundations of the Ming Tombs.\\n\\nRammed earth is extraordinarily durable: sections of the Wall built over 2,000 years ago still stand today, and the platform under the Forbidden City\\'s Hall of Supreme Harmony has carried the hall\\'s weight for six centuries without measurable settlement. In the Fujian tulou, the same technique rose to house-scale fortresses with walls two meters thick, and modern engineers have tested hangtu compositions that rival weak concrete in compressive strength. The Chinese saying \\'a building is only as good as its foundation\\' (geng gao gai lou, di ji yao lao) is literal engineering doctrine.'"
    ),
]

for old, new in replacements:
    if old in src:
        src = src.replace(old, new, 1)
        print('replaced:', old[15:55])
    else:
        print('NOT FOUND:', old[15:55])

open(path, 'w', encoding='utf-8', newline='').write(src)
print('done')
