# Deepen remaining thin dynasty sections: han/tang/song/yuan/ming/qing
path = 'src/data/dynasties.ts'
src = open(path, encoding='utf-8', errors='replace').read()

replacements = [
    # ---- Han: Multi-Story Architecture ----
    (
        "body: 'The Han dynasty pioneered vertical architecture in China. Multi-story watchtowers (que) — often built as paired gate towers flanking palace and tomb entrances — could reach four or five stories, constructed with timber frames infilled with rammed earth or brick. Clay tomb models (mingqi) from Han burials provide detailed evidence of these buildings, showing balconies, bracket sets, and tiled roofs on structures that no longer survive above ground.\\n\\nThe development of mature dougong bracketing made multi-story construction structurally feasible by distributing the weight of upper floors.'",
        "body: 'The Han dynasty pioneered vertical architecture in China. Multi-story watchtowers (que) — often built as paired gate towers flanking palace and tomb entrances — could reach four or five stories, constructed with timber frames infilled with rammed earth or brick. Clay tomb models (mingqi) from Han burials provide detailed evidence of these buildings, showing balconies, bracket sets, and tiled roofs on structures that no longer survive above ground.\\n\\nThe development of mature dougong bracketing made multi-story construction structurally feasible by distributing the weight of upper floors. The mingqi models also document the era\\'s everyday building stock — granaries on stilts, multi-story courtyard mansions, and even the earliest known depictions of the balustraded walkways that would become ubiquitous in Chinese gardens. Because Han timber buildings were almost all destroyed long ago, these miniature clay archives remain the most complete visual record of any early Chinese building period.'"
    ),
    # ---- Han: Buddhist Architecture Arrives ----
    (
        "body: 'The arrival of Buddhism along the Silk Road in the 1st century CE introduced entirely new building types to China. The White Horse Temple (Baima Si) in Luoyang, built in 68 CE, is traditionally recognized as the first Buddhist temple in China. Its architecture adapted Indian stupa and vihara forms to Chinese building techniques, creating a hybrid style that would evolve into the iconic Chinese pagoda. Buddhist architecture brought with it new spatial concepts — the circumambulation path around a central stupa, the assembly hall for monastic chanting, and the progressive revelation of sacred space through sequential courtyards.'",
        "body: 'The arrival of Buddhism along the Silk Road in the 1st century CE introduced entirely new building types to China. The White Horse Temple (Baima Si) in Luoyang, built in 68 CE, is traditionally recognized as the first Buddhist temple in China. Its architecture adapted Indian stupa and vihara forms to Chinese building techniques, creating a hybrid style that would evolve into the iconic Chinese pagoda.\\n\\nBuddhist architecture brought with it new spatial concepts — the circumambulation path around a central stupa, the assembly hall for monastic chanting, and the progressive revelation of sacred space through sequential courtyards. The transformation was two-way: Indian stupa mounds became Chinese multi-story towers, while the Buddhist demand for procession space reinforced and monumentalized the axial courtyard plan already native to China. By the end of the Han, pagodas and temple compounds had begun to appear across the empire, setting the pattern every later dynasty would inherit.'"
    ),
    # ---- Han: Tomb Architecture and the Afterlife ----
    (
        "body: 'Han tombs were conceived as underground palaces for the deceased, complete with living quarters, kitchens, stables, and entertainment spaces. The most elaborate tombs featured vaulted brick ceilings, stone-carved doorways, and wall paintings depicting the daily life of the deceased.\\n\\nInscriptions and ceremonial objects placed within tombs provide invaluable evidence of Han building practices, since most above-ground structures from this period have been lost. The que towers that marked tomb entrances were scaled-down versions of the gate towers at real palaces, ensuring the deceased maintained their status in the afterlife.'",
        "body: 'Han tombs were conceived as underground palaces for the deceased, complete with living quarters, kitchens, stables, and entertainment spaces. The most elaborate tombs featured vaulted brick ceilings, stone-carved doorways, and wall paintings depicting the daily life of the deceased — hunts, banquets, musicians, and the granaries and kitchens that sustained the household.\\n\\nInscriptions and ceremonial objects placed within tombs provide invaluable evidence of Han building practices, since most above-ground structures from this period have been lost. The que towers that marked tomb entrances were scaled-down versions of the gate towers at real palaces, ensuring the deceased maintained their status in the afterlife. The most spectacular surviving example, the Wu Family Shrines in Shandong (147-168 CE), preserves carved stone reliefs of entire building complexes — pavilions, gates, and ancestral halls — rendered with the precision of architectural drawings, an irreplaceable record of Han construction.'"
    ),
    # ---- Tang: The Golden Age of Proportion ----
    (
        "body: 'Tang architecture is characterized by bold, confident proportions. Columns are thick and widely spaced, roofs sweep outward in dramatic overhangs, and the overall composition conveys strength and monumentality. The dougong brackets of Tang buildings are massive and primarily structural, transferring roof weight directly to columns — unlike later periods where brackets became smaller and more decorative. This structural honesty gives Tang buildings their distinctive character: powerful, unadorned, and architecturally legible.'",
        "body: 'Tang architecture is characterized by bold, confident proportions. Columns are thick and widely spaced, roofs sweep outward in dramatic overhangs, and the overall composition conveys strength and monumentality. The dougong brackets of Tang buildings are massive and primarily structural, transferring roof weight directly to columns — unlike later periods where brackets became smaller and more decorative.\\n\\nThe surviving evidence makes the contrast vivid: at the East Hall of Foguang Temple (857 CE), the brackets rise about 2.5 meters — half the height of the columns themselves — and project the eaves nearly 4 meters past the wall. Later Ming-Qing builders shrank equivalent brackets into dense ornament and hid the real loads behind the ceiling. This structural honesty gives Tang buildings their distinctive character: powerful, unadorned, and architecturally legible, the closest Chinese architecture ever came to the exposed engineering of a Gothic cathedral.'"
    ),
    # ---- Song: The Yingzao Fashi ----
    (
        "body: 'In 1103, the Song government published the Yingzao Fashi (Treatise on Architectural Methods), the world\\'s first state-issued building code. Compiled by the architect Li Jie, this comprehensive manual specified everything from timber sizing and joinery techniques to decorative painting and cost estimation.\\n\\nThe Yingzao Fashi introduced the cai-fen modular system, where all building dimensions were derived from a standard timber cross-section measurement. This modular approach allowed prefabrication of components and standardized construction across the empire, yet permitted enough flexibility for regional variation and artistic expression.'",
        "body: 'In 1103, the Song government published the Yingzao Fashi (Treatise on Architectural Methods), the world\\'s first state-issued building code. Compiled by the architect Li Jie, this comprehensive manual specified everything from timber sizing and joinery techniques to decorative painting and cost estimation — even down to the number of workmen required to move a given timber and the exact wages they were to be paid.\\n\\nThe Yingzao Fashi introduced the cai-fen modular system, where all building dimensions were derived from a standard timber cross-section measurement. This modular approach allowed prefabrication of components and standardized construction across the empire, yet permitted enough flexibility for regional variation and artistic expression. The manual\\'s 34 chapters, with their detailed diagrams of brackets, beams, and roof framing, remained the definitive reference for Chinese builders for 800 years — and are still used today to authenticate and restore Song-era structures.'"
    ),
    # ---- Song: Garden Architecture as High Art ----
    (
        "body: 'Song dynasty literati elevated garden design to a refined art form. Unlike the vast imperial hunting parks of earlier dynasties, Song gardens were intimate spaces designed for contemplation, poetry, and scholarly gatherings. Natural rock formations — often transported at great expense from distant mountains — were arranged to evoke mountain landscapes in miniature. Pavilions, covered walkways, and moon gates framed carefully composed views. The principles established in Song gardens — borrowed scenery (jiejing), the interplay of solid and void, and the seasonal transformation of plants — became foundational to Chinese garden design.'",
        "body: 'Song dynasty literati elevated garden design to a refined art form. Unlike the vast imperial hunting parks of earlier dynasties, Song gardens were intimate spaces designed for contemplation, poetry, and scholarly gatherings. Natural rock formations — often transported at great expense from distant mountains — were arranged to evoke mountain landscapes in miniature. Pavilions, covered walkways, and moon gates framed carefully composed views.\\n\\nThe Song garden was a setting for social performance as much as retreat: literati held poetry competitions in the pavilions, painted the views from the studios, and planted flowers by species whose meanings they traded in verse. The principles established in Song gardens — borrowed scenery (jiejing), the interplay of solid and void, and the seasonal transformation of plants — became foundational to Chinese garden design, and their fullest surviving expression can be seen in the Ming-Qing classical gardens of Suzhou.'"
    ),
    # ---- Yuan: The Cosmopolitan Court ----
    (
        "body: 'Kublai Khan\\'s Yuan court was the most cosmopolitan in Chinese history. Architects, craftsmen, and artists from across the Mongol Empire — Persia, Central Asia, Nepal, and Tibet — worked alongside Chinese builders in the new capital of Dadu. The court employed Muslim engineers to design astronomical observatories and hydraulic systems, Nepalese sculptors to create Buddhist imagery, and Persian artisans to introduce new decorative techniques including cobalt-blue ceramic glazes.\\n\\nThis unprecedented cultural mixing produced a uniquely hybrid architecture.'",
        "body: 'Kublai Khan\\'s Yuan court was the most cosmopolitan in Chinese history. Architects, craftsmen, and artists from across the Mongol Empire — Persia, Central Asia, Nepal, and Tibet — worked alongside Chinese builders in the new capital of Dadu. The court employed Muslim engineers to design astronomical observatories and hydraulic systems, Nepalese sculptors to create Buddhist imagery, and Persian artisans to introduce new decorative techniques including cobalt-blue ceramic glazes.\\n\\nThe most famous of these imported masters was Araniko, a Nepalese architect brought to court in 1260 at the age of 17, who rose to direct the empire\\'s imperial building office and designed the White Stupa of Miaoying Temple. This unprecedented cultural mixing produced a uniquely hybrid architecture — one in which the timber courtyard tradition coexisted with masonry stupas, tent-like ceremonial halls, and the first glazed-tile buildings in blue-and-white.'"
    ),
    # ---- Yuan: Tibetan Buddhist Architecture ----
    (
        "body: 'The Yuan emperors\\' conversion to Tibetan Buddhism (Lamaism) introduced a new architectural tradition to China. White stupas (dagobas) — solid, bell-shaped monuments of Tibetan origin — became prominent landmarks in the capital. The White Stupa of Miaoying Temple, designed by the Nepalese architect Araniko in 1271, rises 50.9 meters and remains one of Beijing\\'s oldest intact structures. Tibetan Buddhist temples, with their distinctive hall plans organized around circumambulation paths and central deity platforms, contrasted sharply with traditional Chinese axial courtyard layouts.'",
        "body: 'The Yuan emperors\\' conversion to Tibetan Buddhism (Lamaism) introduced a new architectural tradition to China. White stupas (dagobas) — solid, bell-shaped monuments of Tibetan origin — became prominent landmarks in the capital. The White Stupa of Miaoying Temple, designed by the Nepalese architect Araniko in 1271, rises 50.9 meters and remains one of Beijing\\'s oldest intact structures.\\n\\nTibetan Buddhist temples, with their distinctive hall plans organized around circumambulation paths and central deity platforms, contrasted sharply with traditional Chinese axial courtyard layouts. Where the Chinese temple leads the visitor forward along a straight axis to a hall of worship, the Tibetan tradition walks the devotee around a central image in a clockwise circuit. The two systems would eventually merge: Yuan-built temples combined Tibetan stupa and mandala elements with Chinese halls, creating the hybrid temples that reached their full flowering at the Qing court in Beijing and Chengde.'"
    ),
    # ---- Ming: The Great Wall Reborn in Brick ----
    (
        "body: 'The Ming dynasty transformed the Great Wall from earlier rammed-earth fortifications into the stone-and-brick structure visible today. Ming builders faced the wall with fired brick and stone, constructed watchtowers at regular intervals, and incorporated beacon towers for smoke-signal communication.\\n\\nThe Ming wall was not a single defensive line but an integrated system of walls, fortresses, signal towers, and garrison towns stretching over 8,850 kilometers. The sections most visited today — Badaling, Mutianyu, Jinshanling — are all Ming construction.'",
        "body: 'The Ming dynasty transformed the Great Wall from earlier rammed-earth fortifications into the stone-and-brick structure visible today. Ming builders faced the wall with fired brick and stone, constructed watchtowers at regular intervals, and incorporated beacon towers for smoke-signal communication — a network so effective that a signal from the frontier could reach the capital in under a day.\\n\\nThe Ming wall was not a single defensive line but an integrated system of walls, fortresses, signal towers, and garrison towns stretching over 8,850 kilometers, defended by hundreds of thousands of garrison troops and, in the north, standardized logistics of lime and brick. The sections most visited today — Badaling, Mutianyu, Jinshanling — are all Ming construction, and even the much-photographed crenellations follow a military manual: merlons with arrow slits on the outer face, a parapet wall on the inner side, and drainage channels to keep the wall\\'s core from freezing and cracking.'"
    ),
    # ---- Ming: The Cai-Fen Modular System ----
    (
        "body: 'Ming architects refined the cai-fen modular system inherited from the Song dynasty. Under this system, the cross-section of a standard timber bracket (the cai) determined all other building dimensions: column height, beam span, roof slope, and decorative detail. This modularity enabled rapid construction, standardized component production, and ensured proportional harmony across buildings of different scales. A minor official\\'s residence and the emperor\\'s throne hall used the same proportional system — differing only in the size of the base module.'",
        "body: 'Ming architects refined the cai-fen modular system inherited from the Song dynasty. Under this system, the cross-section of a standard timber bracket (the cai) determined all other building dimensions: column height, beam span, roof slope, and decorative detail. This modularity enabled rapid construction, standardized component production, and ensured proportional harmony across buildings of different scales.\\n\\nIts power was demonstrated at the largest scale ever attempted: the Forbidden City\\'s 980 buildings rose in just 14 years (1406-1420) because columns, beams, and brackets were prefabricated in workshops across the empire and assembled on site like a giant kit. A minor official\\'s residence and the emperor\\'s throne hall used the same proportional system — differing only in the size of the base module. This is the deep reason Chinese architecture looks so consistent: one mathematical language, applied at every rank.'"
    ),
    # ---- Qing: Garden Architecture at Its Peak ----
    (
        "body: 'The Qing dynasty represents the pinnacle of Chinese garden design. The Summer Palace (Yiheyuan), rebuilt by the Empress Dowager Cixi in 1886, is the largest and best-preserved imperial garden in China. It combines Kunming Lake, Longevity Hill, and hundreds of pavilions, halls, and covered corridors into a unified composition where architecture and nature are inseparable.\\n\\nThe 728-meter Long Corridor — the longest painted gallery in the world — contains over 14,000 paintings depicting Chinese landscapes, legends, and historical scenes. At Chengde, the Mountain Resort integrated Tibetan, Mongolian, and Han Chinese architectural styles into gardens that replicated famous landscapes from across the empire.'",
        "body: 'The Qing dynasty represents the pinnacle of Chinese garden design. The Summer Palace (Yiheyuan), rebuilt by the Empress Dowager Cixi in 1886, is the largest and best-preserved imperial garden in China. It combines Kunming Lake, Longevity Hill, and hundreds of pavilions, halls, and covered corridors into a unified composition where architecture and nature are inseparable.\\n\\nThe 728-meter Long Corridor — the longest painted gallery in the world — contains over 14,000 paintings depicting Chinese landscapes, legends, and historical scenes. At Chengde, the Mountain Resort integrated Tibetan, Mongolian, and Han Chinese architectural styles into gardens that replicated famous landscapes from across the empire — the Kangxi and Qianlong emperors even had their favorite southern scenes, like the Suzhou-style gardens of the Jiangnan region, rebuilt at a fraction of their original scale. Qing gardens were not escapist fantasy but imperial statecraft in landscape form: microcosms that claimed mastery over the entire empire.'"
    ),
    # ---- Qing: The Last Imperial Building Code ----
    (
        "body: 'The Gongcheng Zuofa Zeli (Engineering Methods and Regulations), published in 1734, was the final comprehensive building code of imperial China. It standardized construction practices for all official buildings: dimensions, proportions, materials, decorative patterns, and cost estimates. The manual included detailed illustrations of joinery, bracket assembly, and roof framing. While building on Song and Ming precedents, the Qing code reflected the dynasty\\'s preference for standardized efficiency over architectural innovation — a shift that paralleled the Qing state\\'s emphasis on administrative control.'",
        "body: 'The Gongcheng Zuofa Zeli (Engineering Methods and Regulations), published in 1734, was the final comprehensive building code of imperial China. It standardized construction practices for all official buildings: dimensions, proportions, materials, decorative patterns, and cost estimates. The manual included detailed illustrations of joinery, bracket assembly, and roof framing — and prescribed the exact ratios that produced the Qing style\\'s characteristic slender columns and dense decorative brackets.\\n\\nWhile building on Song and Ming precedents, the Qing code reflected the dynasty\\'s preference for standardized efficiency over architectural innovation — a shift that paralleled the Qing state\\'s emphasis on administrative control. Its practical consequence can still be measured in Beijing\\'s surviving Qing-era architecture: thousands of halls share the same proportions and details, built to spec by a state that valued uniformity as much as splendor.'"
    ),
]

for old, new in replacements:
    if old in src:
        src = src.replace(old, new, 1)
        print('replaced:', old[15:55])
    else:
        print('NOT FOUND:', old[15:55])

open(path, 'w', encoding='utf-8', newline='').write(src)
print('done')
