# Deepen zhou & qin sections in dynasties.ts (literal \n\n preserved via \\n\\n)
path = 'src/data/dynasties.ts'
src = open(path, encoding='utf-8', errors='replace').read()

replacements = [
    # ---- Zhou: The Birth of Building Codes ----
    (
        "body: 'The Zhou dynasty formalized architecture through the ritual text Zhou Li (Rites of Zhou), which prescribed building dimensions, decoration, and layout according to strict social hierarchy. A feudal lord\\'s main hall could not exceed the emperor\\'s in width or height; the number of courtyards, the type of roof tiles, and even the color of painted columns were regulated by rank.\\n\\nThis codification ensured that architecture visually reinforced the social order — a principle that would govern Chinese building for three millennia.'",
        "body: 'The Zhou dynasty formalized architecture through the ritual text Zhou Li (Rites of Zhou), which prescribed building dimensions, decoration, and layout according to strict social hierarchy. A feudal lord\\'s main hall could not exceed the emperor\\'s in width or height; the number of courtyards, the type of roof tiles, and even the color of painted columns were regulated by rank.\\n\\nThe rules were not abstract theory — bronze inscriptions record actual enforcement. The Zhengting Yin (Rectification Decree) of 9th-century BCE Zhou, preserved on the court bronze vessels, records how King Xuan sent officials to inspect the capitals of feudal lords and punish those whose palace plans exceeded their rank. Building law was constitutional law: architecture was the most visible map of who stood where in the social order, and this codification ensured it visually reinforced that hierarchy for the next three millennia.'"
    ),
    # ---- Zhou: The Siheyuan Courtyard House ----
    (
        "body: 'The classic Chinese courtyard house took its mature form during the Zhou. A siheyuan consisted of buildings arranged around a central open space, with the main hall facing south to capture winter sunlight and deflect cold northern winds.\\n\\nSide halls housed family members according to seniority, while the southern building served as an entrance and servants\\' quarters. This layout was not merely practical — it embodied Confucian family hierarchy and the cosmological relationship between earth (the courtyard) and the surrounding structures.'",
        "body: 'The classic Chinese courtyard house took its mature form during the Zhou. A siheyuan consisted of buildings arranged around a central open space, with the main hall facing south to capture winter sunlight and deflect cold northern winds.\\n\\nSide halls housed family members according to seniority — the east hall outranking the west, since the rising sun faced the family\\'s eldest son — while the southern building served as an entrance and servants\\' quarters. Excavated Zhou foundations at Fengxi and Luoyang confirm the pattern: a raised main hall on a rammed-earth platform, flanking wings at right angles, and a gate house on the axis, all facing south. This layout was not merely practical — it embodied Confucian family hierarchy and the cosmological relationship between earth (the courtyard) and the surrounding structures, and it survives virtually unchanged in the siheyuan of modern Beijing.'"
    ),
    # ---- Zhou: City Walls and Defense ----
    (
        "body: 'Zhou cities were defined by their walls — massive rammed-earth fortifications that could reach 10 meters in height and 20 meters in thickness at the base. The capital city of Haojing was surrounded by a rectangular wall punctuated by gates aligned with the cardinal directions. Within the walls, a grid of streets organized the city into wards, with the royal palace occupying the center. This wall-grid-palace pattern became the template for Chinese urban design, visible in cities from Chang\\'an to Beijing.'",
        "body: 'Zhou cities were defined by their walls — massive rammed-earth fortifications that could reach 10 meters in height and 20 meters in thickness at the base, so wide that chariots could be driven along the top. The capital city of Haojing was surrounded by a rectangular wall punctuated by gates aligned with the cardinal directions; the Kaogong Ji (Record of Trades) later codified the ideal: a square city, three gates per side, a central palace facing south, and an ancestral temple paired with an altar of soil and grain.\\n\\nWithin the walls, a grid of streets organized the city into wards, with the royal palace occupying the center. The Spring and Autumn period (770-476 BCE) multiplied these cities across the map — historical texts record more than 120 walled capitals in the Zhou world — and the wall-grid-palace pattern became the template for Chinese urban design, visible in cities from Chang\\'an to Beijing.'"
    ),
    # ---- Qin: Standardization at Imperial Scale ----
    (
        "body: 'Qin Shi Huang\\'s unification of China extended to architecture through enforced standardization. Bricks, tiles, and building components were manufactured to uniform specifications across the empire, enabling rapid construction and repair of imperial projects.\\n\\nThis standardization was more than practical efficiency — it was a statement of imperial control. It replaced the diverse regional building traditions of the Warring States period with a single, empire-wide architectural language.'",
        "body: 'Qin Shi Huang\\'s unification of China extended to architecture through enforced standardization. Bricks, tiles, and building components were manufactured to uniform specifications across the empire, enabling rapid construction and repair of imperial projects. Excavated Qin bricks carry stamped workshop inscriptions — the maker\\'s name, kiln site, and production date — the world\\'s first quality-control system for building materials, which allowed officials to trace any defective component back to its maker.\\n\\nThe same logic governed transport: standardized axle widths and road gauges meant carts and construction traffic moved freely on the 6,800-kilometer imperial highway network. This standardization was more than practical efficiency — it was a statement of imperial control. It replaced the diverse regional building traditions of the Warring States period with a single, empire-wide architectural language.'"
    ),
    # ---- Qin: The Terracotta Army and Underground Architecture ----
    (
        "body: 'The mausoleum of Qin Shi Huang, discovered in 1974 near Xi\\'an, represents the most ambitious underground architectural project in Chinese history. The tomb complex covers approximately 56 square kilometers and includes not only the famous terracotta warriors but also bronze chariots, subterranean palaces, and mercury-filled rivers representing the waterways of China.\\n\\nThe main tomb chamber, still unexcavated, is described in historical texts as containing a bronze-sheathed palace ceiling inlaid with pearls representing the constellations.'",
        "body: 'The mausoleum of Qin Shi Huang, discovered in 1974 near Xi\\'an, represents the most ambitious underground architectural project in Chinese history. The tomb complex covers approximately 56 square kilometers — roughly the area of Manhattan — and includes not only the famous terracotta army but also bronze chariots, subterranean palace halls, and mercury-filled rivers representing the waterways of China.\\n\\nThe terracotta pits alone are a construction site in miniature: Pit 1, the largest, measures 230 by 62 meters and holds some 6,000 warriors arranged in battle formation, each life-size and individually detailed, standing in corridors once roofed by timber beams. Recent mercury analysis of the mound confirms abnormally high concentrations in the soil — evidence that the mercury rivers described in the Records of the Grand Historian are real. The main tomb chamber, still unexcavated, is described in historical texts as containing a bronze-sheathed palace ceiling inlaid with pearls representing the constellations.'"
    ),
    # ---- Qin: Roads and Infrastructure ----
    (
        "body: 'The Qin built China\\'s first imperial highway network, with standardized road widths and post stations spaced at regular intervals. These roads connected the capital at Xianyang to the farthest reaches of the empire, enabling rapid military movement and administrative control. The Qin also standardized canal construction, linking the Yangtze and Pearl River systems to create a water transport network that would serve Chinese commerce for two millennia.'",
        "body: 'The Qin built China\\'s first imperial highway network, with standardized road widths and post stations spaced at regular intervals. The Zhidao (Straight Road) ran 800 kilometers due north from the capital Xianyang to the frontier at Jiuyuan, driven through mountains and valleys in a near-perfect straight line — its engineers even rerouted it to keep the gradient constant. Sections of Qin road, rammed earth over a gravel base, still survive in Shaanxi after 2,200 years of cart traffic and weather.\\n\\nThese roads connected the capital at Xianyang to the farthest reaches of the empire, enabling rapid military movement and administrative control — the same network that carried the terracotta army\\'s materials to the tomb site. The Qin also standardized canal construction, linking the Yangtze and Pearl River systems to create a water transport network that would serve Chinese commerce for two millennia.'"
    ),
]

for old, new in replacements:
    if old in src:
        src = src.replace(old, new, 1)
        print('replaced:', old[15:60])
    else:
        print('NOT FOUND:', old[15:60])

open(path, 'w', encoding='utf-8', newline='').write(src)
print('done')
